name: Build und Deploy Vite App auf GitHub Pages

on:
  push:
    branches:
      - main # Der Workflow wird bei jedem Push auf den main-Branch ausgeführt
  
  # Ermöglicht manuelles Starten über den Actions Tab in GitHub
  workflow_dispatch:

# WICHTIG: Erforderliche Berechtigungen für das Deployment
permissions:
  contents: write # Erlaubt das Schreiben in den gh-pages Branch
  pages: write    # Erlaubt das Verwalten von GitHub Pages
  id-token: write # Erlaubt das Nutzen des GITHUB_TOKEN

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Code auschecken
        uses: actions/checkout@v4

      - name: 2. Node.js Umgebung einrichten
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          # Caching funktioniert jetzt, da package-lock.json im Root liegt
          cache: 'npm'
          
      - name: 3. Abhängigkeiten installieren
        run: npm ci # Führt "npm ci" im Root aus

      - name: 4. Produktions-Build erstellen (Vite)
        # Führt "npm run build" im Root aus (erzeugt den Ordner "build")
        run: npm run build
        
      - name: 5. Deployment auf GitHub Pages durchführen
        uses: peaceiris/actions-gh-pages@v4 # Beliebte Action für GitHub Pages Deploy
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Pfad zu deinem benutzerdefinierten Build-Ordner
          publish_dir: ./build